dist: trusty
sudo: required
language: node_js
node_js:
  - "6"
os:
  - linux
env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    - DISPLAY=:99.0
before_install:
  - npm install -g npm@4
before_script:
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
script:
  - npm run lint
  - npm run e2e
