dist: trusty
sudo: required
language: node_js
node_js:
  - "6"
npm:
  - "4"
os:
  - linux
env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    - DISPLAY=:99.0
    - CHROME_BIN=chromium-browser
before_script:
  - sh -e /etc/init.d/xvfb start
  - npm install -g npm@4
install:
  - npm install
script:
  - npm run lint
  - npm run e2e
